# Generated by Django 4.2 on 2024-03-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NetworkAnomaliesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_work_state", models.JSONField(default=dict, null=True)),
            ],
            options={
                "db_table": "network_anomalies",
            },
        ),
    ]
