# Generated by Django 4.2 on 2024-02-19 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileHandler',
            new_name='FileHandlerModel',
        ),
    ]
