# Generated by Django 4.2 on 2024-02-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler', '0006_alter_filehandlermodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='filehandlermodel',
            name='file_json',
            field=models.JSONField(default=[], null=True),
        ),
    ]
