# Generated by Django 4.2 on 2024-03-03 04:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("file_handler", "0012_rename_file_json_filehandlermodel_json_of_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filehandlermodel",
            old_name="json_of_file",
            new_name="file_data",
        ),
    ]
