# Generated by Django 4.2 on 2024-03-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_handler", "0023_alter_filehandlermodel_dataset_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetmodel",
            name="val_accuracy",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="datasetmodel",
            name="val_loss",
            field=models.FloatField(default=0.0),
        ),
    ]
