# Generated by Django 4.2 on 2024-02-20 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler', '0003_rename_file_filehandlermodel_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filehandlermodel',
            old_name='files',
            new_name='file',
        ),
    ]
