# Generated by Django 4.2 on 2024-02-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler', '0005_alter_filehandlermodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filehandlermodel',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
