# Generated by Django 4.2 on 2024-02-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler', '0008_alter_filehandlermodel_file_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='filehandlermodel',
            name='file_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
