# Generated by Django 4.2 on 2024-03-03 04:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("file_handler", "0011_filehandlermodel_group_file_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filehandlermodel",
            old_name="file_json",
            new_name="json_of_file",
        ),
    ]
