# Generated by Django 4.2 on 2024-03-03 05:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("file_handler", "0016_alter_filehandlermodel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetmodel",
            name="group_file_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
