# Generated by Django 4.2 on 2024-04-23 04:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("file_handler", "0024_datasetmodel_val_accuracy_datasetmodel_val_loss"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filehandlermodel",
            name="file_data",
        ),
    ]
