# Generated by Django 4.2 on 2024-04-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_handler", "0025_remove_filehandlermodel_file_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetmodel",
            name="sessions_count",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="FileHandlerModel",
        ),
    ]
