# Generated by Django 4.2 on 2024-05-05 13:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("file_handler", "0026_datasetmodel_sessions_count_delete_filehandlermodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datasetmodel",
            name="accuracy",
        ),
        migrations.RemoveField(
            model_name="datasetmodel",
            name="val_accuracy",
        ),
    ]
