# Generated by Django 4.2 on 2024-05-06 04:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("file_handler", "0027_remove_datasetmodel_accuracy_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="datasetmodel",
            old_name="group_file_id",
            new_name="modelID",
        ),
    ]
