# Generated by Django 4.2 on 2024-03-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network_anomalies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="networkanomaliesmodel",
            name="key",
            field=models.IntegerField(default=0),
        ),
    ]
